[tool.poetry]
name = "02"
version = "0.1.0"
description = ""
authors = ["Crhistian Caraballo <cristianjcj35@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
matplotlib = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
